spring:
  application:
    name: first-service
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}  
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
