server:
  port: 7777
  ssl:
    enabled: false
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/lgchintake/config-server-configs
#          default-label: master
#          clone-on-start: true
#          try-master-branch: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}  
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
          