server:
  port: 7777
  ssl:
    enabled: false
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lgchintake/config-server-configs
          clone-on-start: true