eureka:
  instanceId: ${spring.application.name}:${random.int}
  instance:
    preferIpAddress: 'true'
  username: discoveryuser
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@${eureka.ip}:${eureka.port}/eureka/
  password: discovery123
  port: '8888'
spring:
  application:
    name: first-service
server:
  port: '8090'